<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Soif 200</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="./assets/css/style.css" />
</head>
<body>
        <?php require "templates/partials/_header.phtml"; ?>
        <?php require "templates/$template.phtml"; ?>
        <?php require "templates/partials/_footer.phtml"; ?>
</body>
</html>